name: SpigotUHC
version: 0.0.1
author: Stefan Cooper
main: com.stefancooper.SpigotUHC.Plugin
api-version: 1.14
website: https://stefancooper.com
commands:
  uhc:
    description: UHC Related commands
    usage: /uhc --config world.border=500
