name: SpigotUHC
version: 0.0.1
author: Stefan Cooper
main: com.stefancooper.SpigotUHC.Plugin
api-version: 1.14
website: https://stefancooper.com
commands:
  uhc:
    description: Configure and run a UHC
    permission: op
    usage: >
      UHC Plugin Commands
      
      Set config value:
      
      /uhc set world.border.initial.size=500
      
      Set multiple config values:
      
      /uhc set world.border.initial.size=500 world.border.final.size=250
      
      View full config:
      
      /uhc view config
      
      View a specific config value:

      /uhc view world.border.initial.size