name: SpigotUHC
version: 0.0.1
author: Stefan Cooper
main: com.stefancooper.SpigotUHC.Plugin
api-version: 1.14
website: https://stefancooper.com
commands:
  uhc:
    description: Set a UHC config value
    usage: >
      UHC Commands
      
      Set config value:
      
      /uhc set world.border.initial.size=500
      
      Set multiple config values:
      
      /uhc set world.border.final.size=250
