name: Publish plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  COMMIT_SHA: ${{ github.event.after }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Publish
        run: ./publish.sh